DELETE_MEMORY_TOOL_NAME = "DeleteMemory"

DESCRIPTION = (
    "Delete one long-term memory by scope + slug. Irreversible — the "
    "entry is removed from the index and no longer surfaces in future "
    "turns.\n\n"
    "## ALWAYS call before this\n\n"
    "  - `ListUserMemories` (for scope=\"user\") or `ListProjectMemories` "
    "(for scope=\"project\") — to confirm the slug actually exists and "
    "that you're targeting the right entry. Guessing the slug is the "
    "most common way DeleteMemory misses the intended target.\n\n"
    "## When to delete\n\n"
    "  - User explicitly asks to forget something (\"forget that I want "
    "X\", \"drop the deadline memory\").\n"
    "  - Existing entry is wrong AND nothing useful to overwrite it "
    "with. (If there IS a useful replacement — e.g. user changed their "
    "mind — prefer `SaveMemory` with the same slug. Overwrite is "
    "cheaper than delete + create.)\n"
    "  - Project memory references a slide / decision / stakeholder "
    "that no longer exists.\n"
    "  - User-scope memory references an old role / context the user "
    "has clearly moved past.\n\n"
    "## When NOT to delete\n\n"
    "  - User is refining or correcting, not retracting — use "
    "`SaveMemory` with the SAME slug to overwrite. Delete is for "
    "\"this fact should not exist at all\", not \"this fact has "
    "changed\".\n"
    "  - You're unsure whether the entry is stale — leave it. A "
    "slightly outdated memory is cheaper than re-teaching the user a "
    "fact later.\n\n"
    "Returns silently on success; idempotent (deleting a missing slug "
    "still succeeds)."
)
