DELETE_MEMORY_TOOL_NAME = "DeleteMemory"

DESCRIPTION = (
    "Delete one long-term memory by scope + slug. Irreversible — the "
    "entry is removed from the index and no longer surfaces in future "
    "turns.\n\n"
    "## When to delete\n\n"
    "  - The user explicitly asks you to forget something (\"forget that "
    "I want X\", \"drop the deadline memory\").\n"
    "  - You discover an existing entry is wrong and there's no useful "
    "version to overwrite it with. (If there IS — e.g. the user "
    "changed their mind — prefer `SaveMemory` with the same slug; "
    "overwrite is cheaper than delete + create.)\n"
    "  - A project memory references a slide / decision / stakeholder "
    "that no longer exists in the deck.\n"
    "  - A user-scope memory is genuinely stale (e.g. references an "
    "old role the user has since left).\n\n"
    "## When not to delete\n\n"
    "  - The user is refining or correcting, not retracting — use "
    "`SaveMemory` with the same slug to overwrite. Delete only when "
    "the right answer is \"this fact should not exist at all\".\n"
    "  - You're unsure whether the entry is stale — leave it; a slightly "
    "outdated memory in the index is cheaper than asking the user to "
    "re-teach you the same fact later.\n\n"
    "Operates on the same `(scope, slug)` key the other memory tools "
    "use. Returns silently on success; errors only if scope/slug aren't "
    "valid for this caller."
)
