"""Tool description shown to the model."""

SKILL_TOOL_NAME = "Skill"

DESCRIPTION = (
    "Invoke a registered skill by name. Skills are reusable prompt "
    "templates listed in the 'Available skills' section of your system "
    "prompt — call this tool when one matches the user's intent.\n"
    "\n"
    "Two execution modes (the skill author picks via frontmatter; you "
    "don't choose):\n"
    "  - INLINE (default): Skill returns the expanded instruction "
    "template as the tool result. The returned text is *instructions "
    "for you*; read it and follow it in your next response.\n"
    "  - FORK: the skill runs in an isolated sub-loop with its own "
    "tool sandbox and returns only a final summary. You don't see the "
    "intermediate work. Use the `intent` arg below to tell the fork "
    "WHY you're invoking it — without that the fork has no view of the "
    "surrounding work.\n"
    "\n"
    "When to use:\n"
    "  - The user asks for something that matches a skill's description "
    "or whenToUse hint (e.g. 'outline a deck on X' → /outline-deck).\n"
    "  - You want consistent, repeatable behavior for a recurring task.\n"
    "\n"
    "When NOT to use:\n"
    "  - The user explicitly typed a slash command — that's already "
    "handled by the dispatcher; don't re-invoke.\n"
    "  - The task is one-off and no skill matches.\n"
    "\n"
    "Args:\n"
    "  - `name`: skill name without the leading slash (e.g. 'outline-deck'). "
    "Aliases work too. Case-insensitive.\n"
    "  - `args`: arguments string — same as what you'd type after the "
    "slash. Pass empty string if the skill takes no args.\n"
    "  - `intent`: 1-3 sentence rationale for why you're invoking this "
    "skill right now and what surrounding context the skill should keep "
    "in mind. Required for fork-mode skills (the fork loses caller "
    "context otherwise); ignored for inline skills, but always supplying "
    "it is safe and improves transcripts.\n"
    "\n"
    "Output: inline skills return their expanded template; fork skills "
    "return their final answer. Treat either as authoritative for the "
    "task and proceed accordingly."
)
