"""Tool description shown to the model."""

SKILL_TOOL_NAME = "Skill"

DESCRIPTION = (
    "Invoke a registered skill by name. Skills are reusable prompt "
    "templates listed in the 'Available skills' section of your system "
    "prompt — call this tool when one matches the user's intent.\n"
    "\n"
    "How it works: Skill returns the skill's instruction template with "
    "your `args` substituted into ${ARGS}. The returned text is "
    "*instructions for you*, not a final answer. Read the instructions "
    "and follow them in your next response (or via further tool calls).\n"
    "\n"
    "When to use:\n"
    "  - The user asks for something that matches a skill's description "
    "or whenToUse hint (e.g. 'outline a deck on X' → /outline-deck).\n"
    "  - You want consistent, repeatable behavior for a recurring task.\n"
    "\n"
    "When NOT to use:\n"
    "  - The user explicitly typed a slash command — that's already "
    "handled by the dispatcher; don't re-invoke.\n"
    "  - The task is one-off and no skill matches.\n"
    "\n"
    "Args:\n"
    "  - `name`: skill name without the leading slash (e.g. 'outline-deck'). "
    "Aliases work too. Case-insensitive.\n"
    "  - `args`: arguments string — same as what you'd type after the "
    "slash. Pass empty string if the skill takes no args.\n"
    "\n"
    "Output: the skill's expanded instruction template. Treat it as "
    "authoritative for that turn; follow it before adding your own "
    "interpretation."
)
