CREATE_SLIDE_TOOL_NAME = "CreateSlide"

DESCRIPTION = (
    "Create a new presentation slide and add it to the active deck. The "
    "slide renders in the deck preview and exports cleanly to an editable "
    "PowerPoint .pptx via pptxgenjs.\n\n"
    "## `html` — required\n\n"
    "Must be a **complete standalone HTML document** "
    "(`<!DOCTYPE html><html>…</html>`) sized to a standard PowerPoint 16:9 "
    "slide canvas:\n\n"
    "  - Set `body { width: 960px; height: 540px; overflow: hidden; }` and "
    'wrap content in a single `<div class="slide">` of the same '
    "dimensions. All coordinates are measured against this 960×540 "
    "canvas.\n"
    "  - **One absolutely-positioned `<div>` per visible element**, with "
    "explicit `left`, `top`, `width`, `height` in pixels. No flex, no "
    "grid, no padding-based positioning — the .pptx converter ignores "
    "those.\n"
    "  - **One element = one role.** A div is either text OR a shape "
    "(background colour / border, no text), never both. For a coloured "
    "card with text, emit two divs: shape behind, text in front.\n"
    "  - **Inline styles only** on each div (`font-size`, `font-weight`, "
    "`color`, `background`, `border`, `border-radius`, `text-align`, "
    "`font-family`). A minimal top-level `<style>` for `body`/`*` resets "
    "is fine; class- or selector-based CSS won't reach the converter.\n"
    "  - **System fonts only** — e.g. `Arial, Helvetica, sans-serif` for "
    "body or `Georgia, 'Times New Roman', serif` for serif headings. No "
    "Google Fonts, no `@import`, no web fonts (PowerPoint can't render "
    "them).\n"
    "  - **No JavaScript, no `<script>` tags, no `transform`, no "
    "`clip-path`, no animations.** Solid colours; a 2-stop linear "
    "gradient is the most you should use.\n"
    "  - **Bullets are individual divs**, one per line, vertically spaced "
    "~28–36 px. Don't use `<ul>` / `<li>`.\n"
    "  - **Lines/dividers** are thin shape divs (e.g. `height: 2px; "
    "background: #…;`).\n"
    '  - **Images** use `<img src="…" style="position: absolute; '
    'left: …; top: …; width: …; height: …;">` with public HTTP(S) URLs '
    "or data URIs.\n\n"
    "Aim for a clean, professional look: generous whitespace, clear "
    "visual hierarchy, readable font sizes (14–48 px), titles bolder and "
    "larger than body text. **Specific brand, palette, typography, and "
    "tone come from a brand-recipe skill** (see the system prompt's "
    "Slide Brand Routing section); this tool only enforces the "
    "structural contract above.\n\n"
    "## Other args\n\n"
    "  - `title` (optional): short label shown in the deck-panel UI. "
    "Keep it under ~40 chars. Skip for purely decorative or transitional "
    "slides.\n"
    "  - `after_slide_id` (optional): UUID of an existing slide to insert "
    "after. **Omitting or passing null with neither `position` nor "
    "`after_slide_id` inserts at the TOP of the deck, not the end.** "
    "Use `after_slide_id` for one-off inserts; the backend shifts later "
    "slides and runs the call serially.\n"
    "  - `position` (optional): explicit zero-based slot. **Use this "
    "when generating multiple slides in one turn** — pre-compute slot "
    "numbers and emit every create as part of the same assistant "
    "message; the agent loop runs them in parallel, which is "
    "substantially faster than the serial `after_slide_id` path. For a "
    "deck of current length N, the k new slides take positions N, "
    "N+1, …, N+k-1. For a fresh deck, start at 0. The backend "
    "enforces uniqueness on `(project_id, position)`: if you pick a "
    "position that's already taken, the call fails with a clear 400 "
    '("position N is already taken in this project. Pick another '
    'position…") and you retry against the next free slot. '
    "`position` and `after_slide_id` are mutually exclusive.\n\n"
    "## Result\n\n"
    "Returns the new slide's id and position. Keep the id — you need it "
    "for any later `UpdateSlide` / `DeleteSlide` / `ReorderSlide` call.\n\n"
    "Never write slide HTML in the assistant chat message — only through "
    "this tool."
)
