SAVE_USER_MEMORY_TOOL_NAME = "SaveUserMemory"

DESCRIPTION = (
    "Save a long-term memory about THIS USER — preferences, role, "
    "feedback patterns, defaults that apply across every conversation "
    "they have, in any project. Use for facts that would still be true "
    "next month in an unrelated deck.\n\n"
    "## Workflow — follow IN ORDER\n\n"
    "  1. **Confirm scope with the user.** Unless the user's last "
    "message explicitly said this is a user-wide preference (\"always\", "
    "\"in general\", \"for every deck\", \"my default\"), call "
    "`AskUserQuestion` first to confirm whether to save here or to "
    "`SaveProjectMemory`. Memory writes are stateful — never assume "
    "scope.\n"
    "  2. **Call `ListUserMemories`** to see existing slugs. If an "
    "entry on the same topic already exists, REUSE its slug — never "
    "create a sibling that contradicts it.\n"
    "  3. **Save** with the chosen slug, type, name, description, body.\n\n"
    "## When to save\n\n"
    "  - User explicitly asks to remember a preference (\"remember "
    "that I want X\", \"don't forget I prefer Y\").\n"
    "  - User corrects you and the rule should apply to all future "
    "work (\"in general, don't do X\") → `type=\"feedback\"`.\n"
    "  - User confirms a non-obvious cross-project choice was right "
    "(\"yes, that framing was perfect — keep using it\") → "
    "`type=\"feedback\"`.\n"
    "  - You learn the user's role, expertise, default brand, or "
    "working style → `type=\"user\"`.\n"
    "  - User references an external system that applies broadly "
    "(Linear, Slack, dashboards) → `type=\"reference\"`.\n\n"
    "## What NOT to save here\n\n"
    "  - Facts specific to one deck (audience, deadline, this deck's "
    "key message). Those belong in `SaveProjectMemory`.\n"
    "  - Slide content, recent tool results, or anything derivable "
    "from conversation state.\n"
    "  - Transient task progress — lives in TodoWrite.\n\n"
    "## Conflict resolution\n\n"
    "  - **User changed their mind** (\"actually I like emoji now\" "
    "after \"no emoji\") → re-save with the SAME slug. Body captures "
    "the current stance only.\n"
    "  - **User refined / clarified** → re-save with the same slug, "
    "body captures the refined version.\n"
    "  - **User retracted entirely** → call `DeleteMemory` instead.\n"
    "  - **NEVER** create a sibling slug that contradicts an existing "
    "entry. Two slugs disagreeing on the same topic is the failure "
    "mode this workflow exists to prevent.\n\n"
    "## Field rules\n\n"
    "  - `slug`: `[a-z0-9_]+`, ≤64 chars. Examples: `user_role`, "
    "`feedback_no_emoji`, `user_default_brand`, "
    "`reference_linear_project`.\n"
    "  - `type`: one of `user` / `feedback` / `reference`.\n"
    "  - `name`: human-readable title, ≤120 chars.\n"
    "  - `description`: one-line hook for the index, ≤150 chars. "
    "Concrete > vague — next turn's you decides whether to read the "
    "body based on this line alone.\n"
    "  - `body`: full markdown. For `feedback` entries, structure as:\n\n"
    "    ```\n"
    "    <the rule or fact>\n\n"
    "    **Why:** <reason; helps future-you judge edge cases>\n"
    "    **How to apply:** <when/where this applies>\n"
    "    ```"
)
