LIST_PROJECT_MEMORIES_TOOL_NAME = "ListProjectMemories"

DESCRIPTION = (
    "Return the index of long-term memories saved about THIS PROJECT — "
    "audience, deadline, key decisions, brand choices, stakeholders, "
    "references. The result is the index only: each entry's `slug`, "
    "`type`, `name`, and one-line `description`. Use "
    "`ReadMemory(scope=\"project\", slug=...)` to fetch a specific "
    "entry's full body.\n\n"
    "## When to call\n\n"
    "  - Early in a conversation in this project, before any non-trivial "
    "slide work — audience/deadline/key-message likely shape the answer.\n"
    "  - When the request mentions scope, audience, deadline, brand, or "
    "stakeholders.\n"
    "  - After a project switch (your context may carry stale facts from "
    "the previous project).\n"
    "  - When the user references prior project decisions (\"we agreed "
    "to...\", \"the deck angle is...\").\n\n"
    "## When not to call\n\n"
    "  - Purely mechanical operations (single-slide edits, reorders, "
    "deletes) where the project-level facts don't change the action.\n"
    "  - More than once per turn.\n\n"
    "Requires an active project — fails otherwise. The index is bounded "
    "and cheap; bias toward calling when in doubt at the start of a turn."
)
