SAVE_MEMORY_TOOL_NAME = "SaveMemory"

# The "when to save" rules deliberately echo the auto-memory CLAUDE.md
# convention so the model's existing instincts about memory shape carry
# over. Slug must be slug-case (lowercase letters, digits, underscores)
# and is the only stable handle — descriptions and bodies can be edited
# but the slug is the "filename" equivalent.
DESCRIPTION = (
    "Save a long-term memory the agent should carry across future turns.\n\n"
    "## Scopes\n\n"
    "  - `scope=\"user\"`: facts about the user — their role, preferences, "
    "feedback patterns (e.g. \"prefers terse summaries\", \"defaults to "
    "Strategy& brand\"). Loaded for every conversation this user has, in "
    "any project. Use this when the fact would still be true next month "
    "in an unrelated deck.\n"
    "  - `scope=\"project\"`: facts about the active project — audience, "
    "deadline, key message, brand decisions, references to external "
    "systems. Loaded only inside this project's conversations. Use this "
    "when the fact is specific to this deck and wouldn't carry to a "
    "different project. Requires an active project — fails otherwise.\n\n"
    "## When to save\n\n"
    "  - The user explicitly asks you to remember something (\"remember "
    "that I want X\").\n"
    "  - The user corrects your approach in a way that should stick "
    "(\"don't do X\", \"actually do Y\") — save as `type=\"feedback\"`.\n"
    "  - The user confirms a non-obvious approach was right (\"yes, that "
    "framing was perfect\") — also save as `type=\"feedback\"` so you "
    "don't drift away from validated choices.\n"
    "  - You learn the user's role, default brand, or how they like to "
    "work — save as `type=\"user\"`.\n"
    "  - For project scope: when you learn the deck's audience, deadline, "
    "decided key message, or stakeholder voice. Save as `type=\"project\"` "
    "(or `\"decision\"`, `\"stakeholder\"`, `\"reference\"` if more "
    "specific).\n\n"
    "## What NOT to save\n\n"
    "  - Anything already derivable from the conversation or project state "
    "(slide content, recent tool calls, current todos).\n"
    "  - Transient task progress — that lives in TodoWrite, not memory.\n"
    "  - Debugging recipes or one-off fixes — once applied, the fix is in "
    "the deck; it doesn't need a memory entry.\n"
    "  - Duplicate facts — re-saving the same slug is fine and overwrites, "
    "but creating near-duplicate slugs is noise. Check the existing list "
    "(`ListUserMemories` / `ListProjectMemories`) first for major saves.\n\n"
    "## Field rules\n\n"
    "  - `slug`: lowercase letters, digits, and underscores; ≤64 chars. "
    "Examples: `user_role`, `feedback_no_emoji`, `audience`, "
    "`reference_brand_book`. The slug is the addressable handle — pick "
    "one that future-you will recognise at a glance.\n"
    "  - `type`: a short tag for the category. User scope: `user` / "
    "`feedback` / `reference`. Project scope: `project` / `reference` / "
    "`stakeholder` / `decision`.\n"
    "  - `name`: human-readable title, ≤120 chars.\n"
    "  - `description`: one-line hook shown in the index, ≤150 chars. The "
    "model (you, next turn) will decide whether to read the full body "
    "based on this line — write it as concretely as possible.\n"
    "  - `body`: full content as markdown. For feedback/project entries, "
    "structure as:\n\n"
    "    ```\n"
    "    <the rule or fact>\n\n"
    "    **Why:** <the reason; helps future-you judge edge cases>\n"
    "    **How to apply:** <when/where this applies>\n"
    "    ```\n\n"
    "Re-saving an existing `slug` overwrites in place — the slug is the "
    "identity, the rest of the fields are mutable."
)
