SAVE_MEMORY_TOOL_NAME = "SaveMemory"

# The order of sections in this description is deliberate. The workflow
# (check index → pick slug → save) is up top because that's the rule the
# model is most prone to skipping. "When to save" / "What not to save"
# come after.
DESCRIPTION = (
    "Save a long-term memory the agent carries across future turns.\n\n"
    "## Workflow — follow IN ORDER\n\n"
    "  1. **Always** call the matching list tool first:\n"
    "     - `scope=\"user\"` → `ListUserMemories`\n"
    "     - `scope=\"project\"` → `ListProjectMemories`\n"
    "     The index tells you whether an entry on this topic already "
    "exists. Skipping this step is the most common way memory gets "
    "polluted with duplicate or contradictory slugs.\n"
    "  2. **Pick the slug:**\n"
    "     - If the index has an entry on the same topic → reuse THAT "
    "slug. Re-saving overwrites in place. Do not invent a new slug "
    "that contradicts an existing one.\n"
    "     - Otherwise → pick a fresh slug. Lowercase letters, digits, "
    "and underscores only; ≤64 chars; future-you should recognise it "
    "at a glance (e.g. `user_role`, `feedback_no_emoji`, `audience`, "
    "`reference_brand_book`).\n"
    "  3. **Save** with the chosen slug, type, name, description, body.\n\n"
    "## Scopes\n\n"
    "  - `scope=\"user\"`: facts about the user — role, preferences, "
    "feedback patterns, defaults. Loaded across every conversation the "
    "user has, in any project. Use when the fact would still be true "
    "next month in an unrelated deck.\n"
    "  - `scope=\"project\"`: facts about the active project — audience, "
    "deadline, key message, brand decisions, references. Loaded only "
    "inside this project's conversations. Use when the fact is "
    "specific to this deck. Requires an active project — fails "
    "otherwise.\n\n"
    "## When to save\n\n"
    "  - User explicitly asks (\"remember that I want X\").\n"
    "  - User corrects you in a way that should stick (\"don't do X\", "
    "\"actually do Y\") → `type=\"feedback\"`.\n"
    "  - User confirms a non-obvious choice was right (\"yes, that "
    "framing was perfect\") → `type=\"feedback\"` so you don't drift "
    "away from validated decisions next turn.\n"
    "  - You learn the user's role, default brand, or working style → "
    "`type=\"user\"`.\n"
    "  - For project scope: learn the deck's audience, deadline, key "
    "message, stakeholder voice → `type=\"project\"` / `\"decision\"` / "
    "`\"stakeholder\"` / `\"reference\"`.\n\n"
    "## What NOT to save\n\n"
    "  - Slide content, recent tool results, current todos — already "
    "derivable from conversation state.\n"
    "  - Transient task progress — that lives in TodoWrite.\n"
    "  - Debugging recipes or one-off fixes — the fix is in the deck.\n\n"
    "## Conflict resolution (when the index already has a related entry)\n\n"
    "  - **User changed their mind** (\"actually I like emoji now\" after "
    "\"no emoji\") → re-save with the SAME slug. Body captures the "
    "current stance only; do not preserve the old one. The upsert "
    "overwrites in place.\n"
    "  - **User refined / clarified** → re-save with the same slug, "
    "body captures the refined version.\n"
    "  - **User retracted entirely** (\"forget that, I don't have a "
    "preference\") → call `DeleteMemory(scope, slug)` instead of "
    "saving.\n"
    "  - **NEVER** create a sibling slug that contradicts an existing "
    "entry. Two slugs disagreeing on the same topic is the failure "
    "mode this whole workflow exists to prevent.\n\n"
    "## Field rules\n\n"
    "  - `slug`: `[a-z0-9_]+`, ≤64 chars.\n"
    "  - `type`: user-scope = `user`/`feedback`/`reference`; "
    "project-scope = `project`/`reference`/`stakeholder`/`decision`.\n"
    "  - `name`: human-readable title, ≤120 chars.\n"
    "  - `description`: one-line hook shown in the index, ≤150 chars. "
    "Concrete > vague — next turn's you will decide whether to read the "
    "body based ONLY on this line.\n"
    "  - `body`: full markdown. For feedback/decision entries, "
    "structure as:\n\n"
    "    ```\n"
    "    <the rule or fact>\n\n"
    "    **Why:** <reason; helps future-you judge edge cases>\n"
    "    **How to apply:** <when/where this applies>\n"
    "    ```"
)
